stripe:
  key:
    public: pk_test_51KxqZnJNW48ppxohCUZXy9omYqgF6AFXqv9w0w7Ar4yTWtepKdXYy7Xn7j0sKXguJeUaRUcyeEwyaGjAvdyDbWp200MbIhld0m
    secret: sk_test_51KxqZnJNW48ppxohaUj8dk2WUAb1A3GQfTcYjJ4AOX9p7UcbjYZeMjv0HxXEDf3N5TCNStq9PkknIpHNArOghQAI00LMPqphuS
